# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PitchVenture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PitchVenture
  pod 'IQKeyboardManagerSwift', '6.5.9'
  pod 'SVProgressHUD', '2.2.5'

end
